apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: shiva2720/http-server-1
        ports:
        - containerPort: 8000
